[package]
name = "tui2"
version = "0.1.0"
edition = "2024"
authors = ["Austin"]
description = "A terminal UI launcher for terminal UI apps"
repository = "https://github.com/therobustroast/tui2"
homepage = "https://github.com/therobustroast/tui2"
license = "MIT"
readme = "README.md"

[dependencies]
crossterm = "0.28"
ratatui = "0.29"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
